version: 2.0
jobs:
  "node-8":
    working_directory: ~/cra-8
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      - run:
          name: npm test
          command: npm test
      - run:
          name: npm run build
          command: npm run build
  "node-10":
    working_directory: ~/cra-10
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      - run:
          name: npm test
          command: npm test
      - run:
          name: npm run build
          command: npm run build

workflows:
  version: 2
  build:
    jobs:
      - "node-8"
      - "node-10"
